[pytest]
filterwarnings =
    ignore:Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
    ignore:The default value of `allowed_objects` will change in a future version.:langchain_core._api.deprecation.LangChainPendingDeprecationWarning
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16
